function Hd = FD1
%FD1 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
% Generated on: 10-Aug-2016 09:46:19

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in kHz.
Fs = 352800;  % Sampling Frequency

N     = 502;    % Order
Fpass = 20000;  % Passband Frequency
Fstop = 24100;  % Stopband Frequency
Wpass = 1;      % Passband Weight
Wstop = 160000;  % Stopband Weight
dens  = 16;     % Density Factor

% Calculate the coefficients using the FIRPM function.
b1  = firpm(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop], ...
           {dens});
b1 = upsample( b1, 16 );
b1 = b1( 1 : length(b1) - 15 );
Hd1 = dfilt.dffir(b1);

% All frequency values are in kHz.
Fs = 5644800;  % Sampling Frequency

N     = 160;     % Order
Fpass = 20000;   % Passband Frequency
Fstop = 332800;  % Stopband Frequency
Wpass = 1;       % Passband Weight
Wstop = 60000;   % Stopband Weight
dens  = 16;      % Density Factor

% Calculate the coefficients using the FIRPM function.
b2  = firpm(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop], ...
           {dens});
Hd2 = dfilt.dffir(b2);

ND2 = N/2;
Hd = conv( b1, b2 );
%Hd = Hd( ND2 + 1 : length( Hd ) - ND2 );
Hd = Hd * 0.995/max(Hd);

%fvtool(Hd1, Hd2 );

% [EOF]
