function Hd = FIRL1
%FIR1 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the Signal Processing Toolbox 7.0.
% Generated on: 25-Apr-2016 06:13:35

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 176400;  % Sampling Frequency - 4Fs

N     = 238;    % Order
Fpass = 20000;  % Passband Frequency
Fstop = 24100;  % Stopband Frequency
Wpass = 1;      % Passband Weight
Wstop = 5000;  % Stopband Weight
dens  = 20;     % Density Factor

% Calculate the coefficients using the FIRPM function.
h1 = firpm(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop], ...
           {dens});
h1 = upsample( h1, 4 );

Fs = 705600;  % Sampling Frequency - 4Fs * 4Fs = 16Fs

N     = 64;     % Order
Fpass = 20000;  % Passband Frequency
Fstop = 156400;  % Stopband Frequency
Wpass = 1;      % Passband Weight
Wstop = 5000;  % Stopband Weight
dens  = 20;     % Density Factor

% Calculate the coefficients using the FIRPM function.
h2 = firpm(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop], ...
           {dens});
%fvtool( dfilt.dffir( h1 ), dfilt.dffir( h2 ) );
h2 = conv( h1, h2 );
Hd = h2( 1 : length( h2 ) - 3 );

% [EOF]
