function Hd = FIRL2
%FIR2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the Signal Processing Toolbox 7.0.
% Generated on: 25-Apr-2016 06:23:21

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 22579200;  % Sampling Frequency

N     = 256;     % Order
Fpass = 20000;   % Passband Frequency
Fstop = 685600;  % Stopband Frequency
Wpass = 1;       % Passband Weight
Wstop = 5000;   % Stopband Weight
dens  = 20;      % Density Factor

% Calculate the coefficients using the FIRPM function.
Hd = firpm(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop], ...
           {dens});
%fvtool( dfilt.dffir( Hd ) );

% [EOF]
