function Hd = PPF1
%PPF1 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
% Generated on: 26-Jul-2016 13:53:38

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 705.6;  % Sampling Frequency

Fpass = 20;                % Passband Frequency
Fstop = 24.1;              % Stopband Frequency
Dpass = 0.00057564620966;  % Passband Ripple
Dstop = 1.56227941e-07;    % Stopband Attenuation
dens  = 20;                % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = b;

% [EOF]
