function Hd = PPF2
%PPF2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
% Generated on: 26-Jul-2016 13:56:52

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 22579.2;  % Sampling Frequency

Fpass = 20;                % Passband Frequency
Fstop = 685.6;             % Stopband Frequency
Dpass = 4.9564627261e-05;  % Passband Ripple
Dstop = 1e-08;             % Stopband Attenuation
dens  = 20;                % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = b;

% [EOF]
